orbs:
  aws-eks: circleci/aws-eks@0.2.3
  kubernetes: circleci/kubernetes@0.4.0
version: 2.1

jobs:
  test-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      aws-region:
        description: |
          Region in which resources are deployed
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          aws-region: << parameters.aws-region>>
      - run:
          command: |
            kubectl get services
          name: Test cluster

  update-cluster:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      aws-region:
        description: |
          Region in which resources are deployed
        type: string
    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          aws-region: << parameters.aws-region>>
      - run:
          command: |
            kubectl get services
          name: Test cluster
      - run:
          name: Install envar utility (envsubst)
          command: sudo apt-get install gettext-base
      - run:
          name: Update Cluster
          command: |
            cat yaml/hello-kubernetes.custom-message.tmpl | \
            envsubst > yaml/hello-kubernetes.custom-message.yaml && \
            kubectl apply -f yaml/hello-kubernetes.custom-message.yaml --validate=false
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Image
          command: |
            # docker build --no-cache --build-arg IMAGE_VERSION="1.7" --build-arg IMAGE_CREATE_DATE="`date -u +"%Y-%m-%dT%H:%M:%SZ"`" --build-arg IMAGE_SOURCE_REVISION="`git rev-parse HEAD`" -f Dockerfile -t "hello-kubernetes:1.7" app
            docker build .
            docker images

workflows:
  provision-cluster:
    jobs:
      # - aws-eks/create-cluster:
      #     cluster-name: another-eks-demo
      #     aws-region: us-west-2
      #     context: cdk8s
      # - test-cluster:
      #     cluster-name: another-eks-demo
      #     aws-region: us-west-2
      #     context: cdk8s
      #     requires:
      #       - aws-eks/create-cluster
      # - aws-eks/install-helm-on-cluster:
      #     cluster-name: another-eks-demo
      #     aws-region: us-west-2
      #     context: cdk8s
      #     requires:
      #       - test-cluster
      # - update-cluster:
      #     cluster-name: another-eks-demo
      #     aws-region: us-west-2
      #     context: cdk8s
      #     requires:
      #       - aws-eks/install-helm-on-cluster
      - aws-eks/delete-cluster:
          cluster-name: another-eks-demo
          aws-region: us-west-2
          context: cdk8s
          #requires:
          #  - test-cluster
  # build-app-&-deploy-via-helm:
  #   jobs:
  #     - build
