orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@0.4.0
  slack: circleci/slack@2.0.0
  helm-orb: externalreality/helm-orb@0.0.1
version: 2.1

parameters:
  eks-cluster-name:
    type: string
    default: "null"

jobs:
  test-cluster:
    #executor: cimg/python:3.11.0
    docker:
      - image: cimg/python:3.10
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      aws-region:
        description: |
          Region in which resources are deployed
        type: string
    steps:
      - kubernetes/install
      # - aws-eks/update-kubeconfig-with-authenticator:
      #     cluster-name: << parameters.cluster-name >>
      #     aws-region: << parameters.aws-region>>
      - run:
          command: |
            kubectl get services
          name: Test cluster

  update-cluster:
    docker:
     - image: cimg/python:3.10
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      aws-region:
        description: |
          Region in which resources are deployed
        type: string
    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          aws-region: << parameters.aws-region>>
      - run:
          name: Test cluster
          command: |
            kubectl get services
      - run:
          name: Install envar utility (envsubst)
          command: sudo apt-get update && sudo apt-get install gettext-base
      - run:
          name: Update Cluster
          command: |
            kubectl apply -f app_components/yaml/hello-kubernetes.custom-message.yaml --validate=false
      # - slack/notify:
      #     mentions: 'chris'
      #     webhook: ${SLACK_WEBHOOK}
      #     message: ":fullyoperational: Pipeline: $CIRCLE_WORKFLOW_ID was successful! \n$CIRCLE_BUILD_URL \nhttps://damp-bastion-21277.herokuapp.com/"

  # Workflow "B" will be comprised of a helm specific lifecycle
  helm-lifecycle:
    executor: aws-eks/python3
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      aws-region:
        description: |
          Region in which resources are deployed
        type: string
    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          aws-region: << parameters.aws-region>>
      - run:
          name: Test cluster
          command: |
            kubectl get services
      - helm-orb/install-helm-client
      - helm-orb/install-helm-on-cluster
      - helm-orb/install-helm-chart:
          chart: ./chart/hello/Chart.yaml
          value-files: ./chart/hello/values.yaml
  

workflows:
  provision-awseks-cluster:
    jobs:
      - aws-eks/create-cluster:
          cluster-name: eks-immersion-demo
          aws-region: us-west-2
      - test-cluster:
          cluster-name: eks-immersion-demo
          aws-region: us-west-2
          #context: cdk8s
          requires:
            - aws-eks/create-cluster
      - aws-eks/delete-cluster:
          cluster-name: eks-immersion-demo
          aws-region: us-west-2
          requires:
            - test-cluster
      # - aws-eks/install-helm-on-cluster:
      #     cluster-name: eks-immersion-demo
      #     aws-region: us-west-2
      #     requires:
      #       - aws-eks/create-cluster
      # - update-cluster:
      #     cluster-name: another-eks-demo
      #     aws-region: us-west-2
      #     context: cdk8s
      #     requires:
      #       - aws-eks/install-helm-on-cluster
      # - aws-eks/delete-cluster:
      #     cluster-name: aedifex-eks-test-demo
      #     aws-region: us-west-2
      #     requires:
      #      - aws-eks/create-cluster
  # update-awseks-cluster:
  #   jobs:
  #     - update-cluster:
  #         cluster-name: aedifex-eks-demo
  #         aws-region: us-west-1
  #         # context: cdk8s
