workflows:
  version: 2
  build-test-&-deploy:
    jobs:
      - build-app
      - test-app:
          requires:
            - build-app
      - deploy-app:
          requires:
            - test-app

version: 2
jobs:
  build-app:
    working_directory: ~/project
    docker:
    - image: circleci/node:10.16.3
    steps:
    - setup_remote_docker
    - checkout
    - run:
        name: Update NPM
        command: 'sudo npm install -g npm@latest'
  
  test-app:
    working_directory: ~/project
    docker:
    - image: circleci/node:10.16.3
    steps:
    - checkout
  
  deploy-app:
    working_directory: ~/project
    docker:
    - image: circleci/node:10.16.3
    steps:
    - checkout
