apiVersion: v1
kind: Service
metadata:
  name: aedifex-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: aedifex-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aedifex-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aedifex-app
  template:
    metadata:
      labels:
        app: aedifex-app
    spec:
      containers:
        - name: aedifex-app
          image: 824987503353.dkr.ecr.us-west-2.amazonaws.com/harness:<+pipeline.sequenceId>
          ports:
            - containerPort: 8000
